import Head from "next/head";
import localFont from "next/font/local";
import HomeBanner from "@/component/HomePage/Banner";
import ProjectsHandled from "@/component/HomePage/ProjectsHandled";
import Work from "@/component/HomePage/WorkExperience";
import Skills from "@/component/HomePage/TechnicalSkills";
import CountersSection from "@/component/HomePage/Counter/CounterSection";
// import styles from '../styles/Home.module.scss';
// import "@/styles/globals.scss";
// import { useState } from "react";
// import InputGroup from 'react-bootstrap/InputGroup';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  

  return (
    <>
      <Head>
        <title>Mithun BL - A Passionate Web Developer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <HomeBanner />
        <CountersSection />
        <Skills />
        <Work />
        <ProjectsHandled />
      </div>
    </>
  );
}


{/* <p className="theme-para">Theme is {ddValue ? "Dark" : "Light"}</p> */}

// import Head from "next/head";
// // import Image from "next/image";
// import localFont from "next/font/local";
// import HomeBanner from "@/component/HomePage/Banner";
// import ProjectsHandled from "@/component/HomePage/ProjectsHandled";
// import Work from "@/component/HomePage/WorkExperience";
// import Skills from "@/component/HomePage/TechnicalSkills";
// import CountersSection from "@/component/HomePage/Counter/CounterSection";
// import { useState } from "react";
// import InputGroup from 'react-bootstrap/InputGroup';

// // import styles from "@/styles/Home.module.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export default function Home() {
//   const [ddValue, setDdValue] = useState(false);

// const getDdValue = (e: any) => {
//   const newValue = e.target.checked;
//   setDdValue(newValue);
//   console.log(e, newValue);

//   // Define multiple CSS variables and their values
//   if (newValue) { 
//     const cssVariables = {
//       "--background": '#000',
//       "--black-clr": "#fff",
//     };

//     // Loop through the object and set each CSS variable
//     for (const [property, value] of Object.entries(cssVariables)) {
//       document.documentElement.style.setProperty(property, value);
//     }
//   } else {
//     // Reset the CSS variables to their original values if the checkbox is unchecked
//     const cssVariables = {
//       "--background": "#fff",
//       "--black-clr": "#000",
//     };

//     for (const [property, value] of Object.entries(cssVariables)) {
//       document.documentElement.style.setProperty(property, value);
//     }
//   }
// };

//   // const [ddValue, setDdValue] = useState(false);

//   // const getDdValue = (e: any) => {
//   //   const newValue = e.target.checked;
//   //   setDdValue(newValue);
//   //   console.log(e, newValue);
  
//   //   // Define multiple CSS variables and their values
//   //   if(ddValue)
//   //   { 
//   //     const cssVariables = {
//   //       "--background":'#000',
//   //       "--black-clr": "#fff",
//   //     };
    
//   //     // Loop through the object and set each CSS variable
//   //     for (const [property, value] of Object.entries(cssVariables)) {
//   //       document.documentElement.style.setProperty(property, value);
//   //     }
//   //   }
   
//   // };
  
//   // const getDdValue = (e: any) => {
//   //   const newValue = e.target.value;
//   //   setDdValue(newValue);
//   //   console.log(e);
//   //   document.documentElement.style.setProperty("--blue-clr", "--background", newValue);
//   // };
  
//   return (
//     <>
//       <Head>
//         <title>Portfolio</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//         <div>
//         <InputGroup.Checkbox onChange={getDdValue} aria-label="Checkbox for following text input" />

//         {/* <select name="vinay_dd" id="vinay_dd" >
//         <option value="">Select a color</option>
//         <option value="#ff5733">New Color</option>
//         <option value="#174195">Blue</option>
//         <option value="#fff">White</option>
//         <option value="#000">Black</option>
//       </select> */}

//       <p className="theme-para">{ddValue}</p>
//           <HomeBanner/>
//            <CountersSection/>
//           <ProjectsHandled/>
//           <Work/>
//           <Skills/>
//         </div>
      
//     </>
//   );
// }




// {/* <div
//         className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
//       >
//         <main className={styles.main}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js logo"
//             width={180}
//             height={38}
//             priority
//           />
//           <ol>
//             <li>
//               Get started by editing <code>src/pages/index.tsx</code>.
//             </li>
//             <li>Save and see your changes instantly.</li>
//           </ol>

//           <div className={styles.ctas}>
//             <a
//               className={styles.primary}
//               href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               <Image
//                 className={styles.logo}
//                 src="/vercel.svg"
//                 alt="Vercel logomark"
//                 width={20}
//                 height={20}
//               />
//               Deploy now
//             </a>
//             <a
//               href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//               className={styles.secondary}
//             >
//               Read our docs
//             </a>
//           </div>
//         </main>
//         <footer className={styles.footer}>
//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <Image
//               aria-hidden
//               src="/file.svg"
//               alt="File icon"
//               width={16}
//               height={16}
//             />
//             Learn
//           </a>
//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <Image
//               aria-hidden
//               src="/window.svg"
//               alt="Window icon"
//               width={16}
//               height={16}
//             />
//             Examples
//           </a>
//           <a
//             href="https://nextjs.org?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <Image
//               aria-hidden
//               src="/globe.svg"
//               alt="Globe icon"
//               width={16}
//               height={16}
//             />
//             Go to nextjs.org →
//           </a>
//         </footer>
//       </div> */}
